project:
  type: website
  output-dir: docs

website:
  title: "Muhammad Suraj Salihu"
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: education.qmd
        text: Education
      - href: projects.qmd
        text: Projects
      - href: research.qmd
        text: Research

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    smooth-scroll: true